[package]
name = "chronos-parser-rs"
version = "0.1.0"
authors = ["Junichi Kato <j5ik2o@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intervals-rs = "0.0.4"
nom = "6"
pom = "3.2.0"
chrono = "0.4.19"